# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanSwiftBuyersGuide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'Alamofire', '5.0.0-beta.6'
pod 'Kingfisher'
pod 'SwiftyJSON'



  # Pods for BuyersGuide

end
