//
//  ListPhoneDetailPresenterTests.swift
//  CleanSwiftBuyersGuide
//
//  Created by Kanjanaporn on 5/9/2562 BE.
//  Copyright (c) 2562 SCBiOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftBuyersGuide
import XCTest

class ListPhoneDetailPresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListPhoneDetailPresenter!
    var viewControllerSpy: ListPhoneDetailViewControllerSpy!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListPhoneDetailPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListPhoneDetailPresenter() {
        sut = ListPhoneDetailPresenter()
        viewControllerSpy = ListPhoneDetailViewControllerSpy()
        sut.viewController = viewControllerSpy
    }

    // MARK: Test doubles

    class ListPhoneDetailViewControllerSpy: ListPhoneDetailViewControllerInterface {
        var listViewModel: ListPhoneDetailModels.SetMobileList.ViewModel?
        var imageView: GetImage.ViewModel?
        func displayedListPhone(viewModel: ListPhoneDetailModels.SetMobileList.ViewModel) {
            listViewModel = viewModel
        }

        func displayImage(viewModel: GetImage.ViewModel) {
            imageView = viewModel
        }
    }

    // MARK: Tests

    func testPresentListDetail() {
        // Given
        let response = ListPhoneDetailModels.SetMobileList.Response(item: ApiPhone(id: 1, name: "Moto G4 Plus", price: 190.9, thumbImageURL: "", rating: 4.3, description: ""))

        // When
        sut.presentListDetail(reponse: response)

        // Then
        if let response = viewControllerSpy.listViewModel {
            let selectedPhone = ApiPhone(id: 1, name: "Moto G4 Plus", price: 190.9, thumbImageURL: "", rating: 4.3, description: "")
            XCTAssertEqual(response.item, selectedPhone)
        }
    }

    func testPresentImage() {
        let response = GetImage.Response(success: true, Array: [ApiImages(url: "http", id: 1, mobileID: 1)])
//    when
        sut.presentImages(response: response)

//    then
        if let response = viewControllerSpy.imageView {
            let image = ApiImages(url: "http", id: 1, mobileID: 1)
            XCTAssertEqual(response.success, true)
            XCTAssertEqual(response.Array, [image])
        }
    }
}
