//
//  ListPhoneDetailViewControllerTests.swift
//  CleanSwiftBuyersGuide
//
//  Created by Kanjanaporn on 5/9/2562 BE.
//  Copyright (c) 2562 SCBiOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftBuyersGuide
import XCTest

class ListPhoneDetailViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListPhoneDetailViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupListPhoneDetailViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListPhoneDetailViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "ListPhoneDetailViewController") as! ListPhoneDetailViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
//
//  class ListPhoneDetailBusinessLogicSpy: ListPhoneDetailBusinessLogic
//  {
//    var doSomethingCalled = false
//
//    func doSomething(request: ListPhoneDetail.Something.Request)
//    {
//      doSomethingCalled = true
//    }
//  }
  
  // MARK: Tests
  
//  func testShouldDoSomethingWhenViewIsLoaded()
//  {
//    // Given
//    let spy = ListPhoneDetailBusinessLogicSpy()
//    sut.interactor = spy
//
//    // When
//    loadView()
//
//    // Then
//    XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
//  }
//
//  func testDisplaySomething()
//  {
//    // Given
//    let viewModel = ListPhoneDetail.Something.ViewModel()
//
//    // When
//    loadView()
//    sut.displaySomething(viewModel: viewModel)
//
//    // Then
//    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
  }

