//
//  ListPhonePresenterTests.swift
//  CleanSwiftBuyersGuide
//
//  Created by Kanjanaporn on 4/9/2562 BE.
//  Copyright (c) 2562 SCBiOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftBuyersGuide
import XCTest

class ListPhonePresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListPhonePresenter!
    var viewControlerSpy: ListPhoneViewControllerSpy!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListPhonePresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListPhonePresenter() {
        sut = ListPhonePresenter()
        viewControlerSpy = ListPhoneViewControllerSpy()
        sut.viewController = viewControlerSpy
    }

    // MARK: Test doubles

    class ListPhoneViewControllerSpy: ListPhoneViewControllerInterface {
        var listViewModel: ListPhoneModels.GetMobileList.ViewModel?

        func displayListPhone(viewModel: ListPhoneModels.GetMobileList.ViewModel) {
            listViewModel = viewModel
        }

        func displayNavigateView() {
        }

        func displayAlertMaeesage() {
        }
    }

    // MARK: Tests

    func testPresentListPhone() {
        // Given / mock from interacter
        let response = ListPhoneModels.GetMobileList.Response(success: true, Array: [ApiPhone(id: 1, name: "Moto E4 Plus", price: 179.99, thumbImageURL: "https://cdn.mos.cms.futurecdn.net/grwJkAGWQp4EPpWA3ys3YC-650-80.jpg", rating: 4.9, description: "String")])

        // When /
        sut.presentListPhone(response: response)

        // Then
        if let viewModel = viewControlerSpy.listViewModel {
            XCTAssertTrue(viewModel.success)
            XCTAssertEqual(viewModel.Array.count, 1)
            XCTAssertEqual(viewModel.Array[0].name, "Moto E4 Plus")
            XCTAssertEqual(viewModel.Array[0].id, 1)
            XCTAssertEqual(viewModel.Array[0].price, 179.99)
            XCTAssertEqual(viewModel.Array[0].rating, 4.9)

        } else {
            XCTFail()
        }
    }

    func testPresentListPhoneWithEmpty() {
        let response = ListPhoneModels.GetMobileList.Response(success: true, Array: [])
        sut.presentListPhone(response: response)
        if let viewModel = viewControlerSpy.listViewModel {
            XCTAssertEqual(viewModel.Array.count, 0)

        } else {
            XCTFail()
        }
    }

    func testPresentListPhoneSorting() {
        // give
        let response = ListPhoneModels.SortListPhone.Response(Array: [ApiPhone(id: 3, name: "Moto G4 Plus", price: 179, thumbImageURL: "", rating: 4.7, description: "")])
        // when
        sut.presentListPhoneSorting(response: response)

        //then
        if let viewModel = viewControlerSpy.listViewModel {
            let phone = DisplayedPhone(id: 3, name: "Moto G4 Plus", price: 179, thumbImageURL: "", rating: 4.7, description: "")
            XCTAssertEqual(viewModel.Array.count, 1)
            XCTAssertEqual(viewModel.Array[0], phone)
        } else {
            XCTFail()
        }
    }
}
