//
//  ListPhoneInteractorTests.swift
//  CleanSwiftBuyersGuide
//
//  Created by Kanjanaporn on 4/9/2562 BE.
//  Copyright (c) 2562 SCBiOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftBuyersGuide
import XCTest

class ListPhoneInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListPhoneInteractor!
    var presenterSpy: ListPhoneInteractorSpy!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListPhoneInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListPhoneInteractor() {
        sut = ListPhoneInteractor()
        presenterSpy = ListPhoneInteractorSpy()
        sut.presenter = presenterSpy
    }

    // MARK: Test doubles

    class ListPhoneInteractorSpy: ListPhonePresenterInterface {
        var listResponse: ListPhoneModels.GetMobileList.Response?
        var listResponseSorting: ListPhoneModels.SortListPhone.Response?

        func presentListPhone(response: ListPhoneModels.GetMobileList.Response) {
            listResponse = response
        }

        func presentListPhoneSorting(response: ListPhoneModels.SortListPhone.Response) {
            listResponseSorting = response
        }

        func presentNavigate() {
        }
    }

//
    //  // MARK: Tests
    // Given
    func testGetApi() {
    }

    func testGetApiSorting() {
    }

//    // When
//    sut.doSomething(request: request)
//
//    // Then
//    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    //  }
}
