//
//  ListPhoneInteractorTests.swift
//  CleanSwiftBuyersGuide
//
//  Created by Kanjanaporn on 4/9/2562 BE.
//  Copyright (c) 2562 SCBiOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftBuyersGuide
import XCTest

class ListPhoneInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListPhoneInteractor!
    var presenterSpy: ListPhoneInteractorSpy!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListPhoneInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListPhoneInteractor() {
        sut = ListPhoneInteractor()
        presenterSpy = ListPhoneInteractorSpy()
        sut.presenter = presenterSpy
    }

    // MARK: Test doubles

    class ListPhoneInteractorSpy: ListPhonePresenterInterface {
        var listResponse: ListPhoneModels.GetMobileList.Response?
        var listResponseSorting: ListPhoneModels.SortListPhone.Response?

        func presentListPhone(response: ListPhoneModels.GetMobileList.Response) {
            listResponse = response
        }

        func presentListPhoneSorting(response: ListPhoneModels.SortListPhone.Response) {
            listResponseSorting = response
        }

        func presentNavigate() {
        }

        func presentAlertMaeesage() {
        }
    }

    class workerSpy: ListPhoneWorker {
        override func getPhoneInfo(completion: @escaping (Result<[ApiPhone], Error>) -> Void) {
            completion(.success([ApiPhone(id: 0, name: "pro", price: 100.0, thumbImageURL: "", rating: 10.9, description: "")]))
        }
    }

    // MARK: Tests

    // Given
    func testGetApi() {
        sut.worker = workerSpy()
        let request = ListPhoneModels.GetMobileList.Request()
//      when
        sut.getApi(request: request)
//      then
        if let response = presenterSpy.listResponse {
            let phone = ApiPhone(id: 0, name: "pro", price: 100.0, thumbImageURL: "", rating: 10.9, description: "")
            XCTAssertEqual(response.Array, [phone])

        } else {
            XCTFail()
        }
    }

    var arrayList: [ApiPhone] = []
    let list = ApiPhone(id: 0, name: "pro", price: 100.0, thumbImageURL: "", rating: 3.9, description: "")
    let list2 = ApiPhone(id: 1, name: "pro", price: 120.0, thumbImageURL: "", rating: 8.9, description: "")
    let list3 = ApiPhone(id: 2, name: "pro", price: 140.0, thumbImageURL: "", rating: 5.9, description: "")

    func testGetApiSorting() {
//        var arrayList: [ApiPhone] = []
        arrayList.append(list)
        arrayList.append(list2)
        arrayList.append(list3)
        sut.phones = arrayList

        let request = ListPhoneModels.SortListPhone.Request(sortingCase: .highttoLow)
        sut.getApiSorting(request: request)

        if let response = presenterSpy.listResponseSorting {
            XCTAssertEqual(response.Array.count, 3)
            XCTAssertEqual(response.Array[0].id, 2)
        } else {
            XCTFail()
        }
    }

    func testGetApiSortingLowtoHight() {
        arrayList.append(list)
        arrayList.append(list2)
        arrayList.append(list3)
        sut.phones = arrayList

        let request2 = ListPhoneModels.SortListPhone.Request(sortingCase: .lowtoHight)
        sut.getApiSorting(request: request2)
        if let response = presenterSpy.listResponseSorting {
            XCTAssertEqual(response.Array.count, 3)
            XCTAssertEqual(response.Array[0].id, 0)
        } else {
            XCTFail()
        }
    }
}
